name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: .

      - name: Deploy to Azure Web App using Oryx
        uses: azure/appservice-build@v3
        with:
          app-name: jangelucci-hw13
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
